# Dependencies
markdown:            kramdown
highlighter:         rouge


# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               阿宁
tagline:             'To breath,To express,To love'
description:         '好奇，渴望，文本，音乐'
url:                 www.huyuning.com
baseurl:             /
paginate:            7

# About/contact
author:
  name:              bleu
  url:               www.huyuning.com
  email:             huyuning931106@gmail.com

# Custom vers
version:             3.0

# Social Media
github:				https://github.com/BleuHu
twitter:			

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Yixuan Li
  codename:			Geek-green
  link:         https://github.com/YixuanFranco
