# Dependencies
markdown:            kramdown
highlighter:         rouge


# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               阿宁
tagline:             'inner space'
description:         '未来从现实生长。'
url:                 www.huyuning.com
baseurl:             /
paginate:            7

# About/contact
author:
  name:              
  url:               www.huyuning.com
       
# Custom vers
version:             3.0

# Social Media
github:            https://github.com/orderchaos3000

		

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Yixuan Li
  codename:			Geek-green
  link:         https://github.com/YixuanFranco


