# Dependencies
markdown:            kramdown
highlighter:         rouge

# Gems (for Jekyll 3.0)
gems: [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:              阿宁
tagline:             ' What happens when a tornado meets a volcano'
description:         '因好奇心活着，听歌狂魔，文本世界，渴望生活'
url:                 http://huyuning.com
baseurl:             /
paginate:            7

# About/contact
author:
  name:             阿宁
  url:              http://huyuning.com
  email:            huyuning931106@gmail.com
  github:           https://github.com/BleuHu

# Custom vars
version:             2.0

# Social Media
github:				 https://github.com/BleuHu
disqus:             testnaringu

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu
