# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: BleuHu
google_analytics: huyuning BleuHu
title: BleuHu's Blog


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 追本溯源

description: Stylish Jekyll Theme

author:
  name: BleuHu
  email: huyuning931218@126.com
  github: BleuHu
  linkedin: 
  bio: Chase Dream，from back to the future.
  avatar: https://raw.githubusercontent.com/BleuHu/BleuHu.github.io/master/image/avatar.png
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about-me_path: about-me.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
